---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-k8s-discovery-client
spec:
  replicas: 1
  template:
    metadata:
      name: spring-cloud-k8s-discovery-client
      labels:
        app: infrastructure
        serviceType: app
    spec:
      containers:
        - name: spring-cloud-k8s-discovery-client
          image: cloud/spring-cloud-k8s-discovery-client
          ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-k8s-discovery-client
  namespace: default
spec:
  selector:
    serviceType: app
  ports:
    - port: 30081
      targetPort: 30081
      nodePort: 30081 # uncomment for minikube, comment for Kube
  type: NodePort #NodePort for minikube, LoadBalancer for Kube
